
const actionType =  {
    GET_USER_PENDING: "GET_USER_PENDING",
    GET_USER_SUCCESS_EXTERNAL:"GET_USER_SUCCESS_EXTERNAL",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_REJECTED: "GET_USER_REJECTED",
    RESET_USER:"RESET_USER"
  };
  
  export default actionType